### ISSUE TITLE
Actividad 5 Ameli Reyes Hernández 

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-AmeliReyesHernandez#1]
[TIPOS DE TEXTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-AmeliReyesHernandez/files/9635406/TIPOS.DE.TEXTOS.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene un 16 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
